name: Publish Python Package to GitHub Packages

on:
  push:
    branches:
      - main  # Adjust to your main branch
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-latest

    # add permissions to write packages
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "1.3.2"

      - name: Install dependencies
        run: poetry run pip install matplotlib-venn && poetry install

      - name: Build the package
        run: poetry build

      - name: Publish to GitHub Packages
        env:
          POETRY_HTTP_BASIC_GITHUB_USERNAME: ${{ github.actor }}
          POETRY_HTTP_BASIC_GITHUB_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: |
          poetry config repositories.github https://pip.pkg.github.com/${{ github.repository_owner }}
          poetry publish -r github --username $POETRY_HTTP_BASIC_GITHUB_USERNAME --password $POETRY_HTTP_BASIC_GITHUB_PASSWORD

